spring:
  profiles:
#    or use json-logging for logs to be serialized to json
    active: json-logging
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none

renaissancerentals:
  logging:
    enabled: true
  telemetry:
    enabled: true
  mail:
    enabled: true
    clientId: ${GOOGLE_API_CLIENT_ID}
    clientSecret: ${GOOGLE_API_CLIENT_SECRET}
    refreshToken: ${GOOGLE_API_REFRESH_TOKEN}
    tokenServer: https://oauth2.googleapis.com/token
    from: ${MAIL_FROM:renaissance.rentals.mail@gmail.com}
    cc: ${MAIL_CC:edainton@renaissancerentals.com}
    fromName: ${MAIL_FROM_NAME:Renaissance Rentals}
