spring:
  profiles:
#    or use json-logging for logs to be serialized to json
    active: json-logging
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none

renaissancerentals:
  logging:
    enabled: true
  telemetry:
    enabled: true

