<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.renaissancerentals</groupId>
    <artifactId>renaissance-parent</artifactId>
    <version>2.30.0</version>
    <packaging>pom</packaging>
    <name>Renaissance Parent</name>
    <description>Renaissancerentals Parent pom</description>
    <url>https://github.com/renaissancerentals/renaissance-parent</url>
    <licenses>
        <license>
            <name>License</name>
            <url>https://github.com/renaissancerentals/${project.artifactId}/LICENSE</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Contentmunch</name>
            <email>mail@contentmunch.com</email>
            <organization>Contentmunch</organization>
            <organizationUrl>https://www.contentmunch.com</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/renaissancerentals/renaissance-parent.git</connection>
        <developerConnection>scm:git:ssh://github.com/renaissancerentals/renaissance-parent.git</developerConnection>
        <url>https://github.com/renaissancerentals/renaissance-parent</url>
    </scm>
    <properties>
        <java.version>21</java.version>
        <lombok.version>1.18.38</lombok.version>
        <org.mapstruct.version>1.6.3</org.mapstruct.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
    </properties>
    <modules>
        <module>renaissance-bom</module>
        <module>renaissance-foundation-spring-boot-starter</module>
        <module>renaissance-assets-spring-boot-starter</module>
        <module>renaissance-monitor-spring-boot-starter</module>
        <module>renaissance-api-spring-boot-starter</module>
        <module>renaissance-persistence-spring-boot-starter</module>
        <module>renaissance-site-parent</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-instrumentation-bom</artifactId>
                <version>2.15.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.renaissancerentals</groupId>
                <artifactId>renaissance-bom</artifactId>
                <version>2.30.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>net.revelc.code.formatter</groupId>
                    <artifactId>formatter-maven-plugin</artifactId>
                    <version>2.26.0</version>
                    <configuration>
                        <!--suppress UnresolvedMavenProperty -->
                        <configFile>${session.topLevelProject.basedir}/.build-config/formatter.xml</configFile>
                        <encoding>UTF-8</encoding>
                        <lineEnding>LF</lineEnding>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>net.revelc.code</groupId>
                    <artifactId>impsort-maven-plugin</artifactId>
                    <version>1.12.0</version>
                    <configuration>
                        <groups>java.,javax.,org.,com.,com.contentmunch.,</groups>
                        <staticGroups>java,*</staticGroups>
                        <removeUnused>true</removeUnused>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>4.9.3.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${java.version}</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.11.2</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.18.0</version>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>quality</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>net.revelc.code.formatter</groupId>
                        <artifactId>formatter-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>format-code</id>
                                <phase>validate</phase>
                                <goals>
                                    <goal>format</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- Import Sort Plugin -->
                    <plugin>
                        <groupId>net.revelc.code</groupId>
                        <artifactId>impsort-maven-plugin</artifactId>

                        <executions>
                            <execution>
                                <id>sort-imports</id>
                                <phase>validate</phase>
                                <goals>
                                    <goal>sort</goal>
                                </goals>
                            </execution>
                        </executions>

                    </plugin>

                    <!-- SpotBugs Plugin -->
                    <plugin>
                        <groupId>com.github.spotbugs</groupId>
                        <artifactId>spotbugs-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>analyze-spotbugs</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <failOnError>true</failOnError>
                            <effort>Max</effort>
                            <threshold>Medium</threshold>
                            <!--suppress UnresolvedMavenProperty -->
                            <excludeFilterFile>${session.topLevelProject.basedir}/.build-config/spotbugs-exclude.xml</excludeFilterFile>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    <distributionManagement>
        <repository>
            <id>nexus-release</id>
            <url>https://nexus.contentmunch.com/repository/maven-releases/</url>
        </repository>
    </distributionManagement>
</project>
