renaissancerentals:
  assets:
    enabled: true
    clientId: ${GOOGLE_API_CLIENT_ID}
    clientSecret: ${GOOGLE_API_CLIENT_SECRET}
    refreshToken: ${GOOGLE_API_REFRESH_TOKEN}
    tokenServer: https://oauth2.googleapis.com/token
    defaultFolder: ${GOOGLE_DRIVE_FOLDER}
  mail:
    enabled: true
    clientId: ${GOOGLE_API_CLIENT_ID}
    clientSecret: ${GOOGLE_API_CLIENT_SECRET}
    refreshToken: ${GOOGLE_API_REFRESH_TOKEN}
    tokenServer: https://oauth2.googleapis.com/token
    from: ${MAIL_FROM:renaissance.rentals.mail@gmail.com}
    fromName: ${MAIL_FROM_NAME:Renaissance Rentals}
    cc: renaissance.rentals.mail@gmail.com
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
spring:
  profiles:
    active: plain-text-logging
