renaissancerentals:
  assets:
    enabled: true
    clientId: ${GOOGLE_API_CLIENT_ID}
    clientSecret: ${GOOGLE_API_CLIENT_SECRET}
    refreshToken: ${GOOGLE_API_REFRESH_TOKEN}
    tokenServer: https://oauth2.googleapis.com/token
    defaultFolder: ${GOOGLE_DRIVE_FOLDER}
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
spring:
  profiles:
    active: plain-text-logging
