services:
  postgres:
    image: postgres:17.5
    container_name: renaissance-postgres
    restart: always
    environment:
      POSTGRES_USER: renaissance
      POSTGRES_PASSWORD: renaissancepass
      POSTGRES_DB: renaissancedb
    ports:
      - "5434:5432"
    volumes:
      - renaissancedb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U renaissance -d renaissancedb"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  renaissancedb-data:

