<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.renaissancerentals</groupId>
    <artifactId>renaissance-bom</artifactId>
    <version>1.10.0</version>
    <packaging>pom</packaging>
    <name>Renaissance BOM</name>
    <description>Bill of materials for Renaissancerentals libraries</description>
    <url>https://github.com/contentmunch/renaissance-parent/renaissance-bom</url>
    <licenses>
        <license>
            <name>License</name>
            <url>https://github.com/renaissancerentals/renaissance-parent/LICENSE</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Contentmunch</name>
            <email>mail@contentmunch.com</email>
            <organization>Contentmunch</organization>
            <organizationUrl>https://www.contentmunch.com</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/renaissancerentals/renaissance-parent.git</connection>
        <developerConnection>scm:git:ssh://github.com/renaissancerentals/renaissance-parent.git</developerConnection>
        <url>https://github.com/renaissancerentals/renaissance-parent</url>
    </scm>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.5.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.renaissancerentals</groupId>
                <artifactId>renaissance-foundation-spring-boot-starter</artifactId>
                <version>1.10.0</version>
            </dependency>
            <dependency>
                <groupId>com.renaissancerentals</groupId>
                <artifactId>renaissance-assets-spring-boot-starter</artifactId>
                <version>1.10.0</version>
            </dependency>
            <dependency>
                <groupId>com.renaissancerentals</groupId>
                <artifactId>renaissance-monitor-spring-boot-starter</artifactId>
                <version>1.10.0</version>
            </dependency>

            <!-- Mapping related-->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>1.6.3</version>
            </dependency>

            <!--Gmail related-->
            <dependency>
                <groupId>com.google.api-client</groupId>
                <artifactId>google-api-client</artifactId>
                <version>2.7.2</version>
            </dependency>
            <dependency>
                <groupId>com.google.apis</groupId>
                <artifactId>google-api-services-gmail</artifactId>
                <version>v1-rev20250331-2.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.sun.mail</groupId>
                <artifactId>jakarta.mail</artifactId>
                <version>2.0.1</version>
            </dependency>

            <!-- google drive related -->
            <dependency>
                <groupId>com.google.apis</groupId>
                <artifactId>google-api-services-drive</artifactId>
                <version>v3-rev20250427-2.0.0</version>
            </dependency>

            <!-- OpenTelemetry SDK and HTTP instrumentation -->
            <dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-spring-boot-starter</artifactId>
            </dependency>
            <dependency>
                <groupId>net.logstash.logback</groupId>
                <artifactId>logstash-logback-encoder</artifactId>
                <version>8.1</version>
            </dependency>
            <dependency>
                <groupId>io.github.hakky54</groupId>
                <artifactId>logcaptor</artifactId>
                <version>2.11.0</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>0.7.0</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>central</publishingServerId>
                    <autoPublish>true</autoPublish>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>3.2.7</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.18.0</version>
            </plugin>
        </plugins>
    </build>
</project>
