spring:
  application:
    name: renaissance-data
  profiles:
    active: plain-text-logging
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/renaissancedb}
    username: ${SPRING_DATASOURCE_USERNAME:renaissance}
    password: ${SPRING_DATASOURCE_PASSWORD:renaissancepass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:liquibase-changeLog.sql
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
renaissancerentals:
  error:
    notification:
      enabled: true
      email-to: contentmunch@gmail.com
      email-cc: contentmunch@gmail.com
      title-format: ⚠️ Server Exception Alert - {0}
      excluded-server-exceptions:
        - com.renaissancerentals.mail.error.MailServerException
  logging:
    enabled: true
  telemetry:
    enabled: true
  mail:
    enabled: true
    client-id: ${GOOGLE_API_CLIENT_ID}
    client-secret: ${GOOGLE_API_CLIENT_SECRET}
    refresh-token: ${GOOGLE_API_REFRESH_TOKEN}
    token-server: https://oauth2.googleapis.com/token
    from: ${MAIL_FROM:renaissance.rentals.mail@gmail.com}
    cc: ${MAIL_CC:edainton@renaissancerentals.com}
    from-name: ${MAIL_FROM_NAME:Renaissance Rentals}
