spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/renaissancedb
    username: renaissance
    password: renaissancepass
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
  loki:
    environment: local
