Health Restored for Application: ${data.applicationName()}

Time:         ${data.time()}
Endpoint:     ${data.healthEndpoint()}
Previous Status: ${data.previousStatus()}
Downtime Duration: ${data.downtimeDuration()}

The application has recovered and is now reporting a healthy status.

---
This notification was generated by the Renaissancerentals Health Monitor.
