Health Check Failed for Application: ${data.applicationName()}

Time:         ${data.time()}
Endpoint:     ${data.healthEndpoint()}
Status:       ${data.status()}
Error Type:   ${data.errorType()}
Error Since:  ${data.errorSince()}
Retry Count:  ${data.retryCount()}

Error Message:
${data.errorMessage()}

---
This alert was generated by the Renaissancerentals Health Monitor.
